Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Controllers/ArchiveController.cs
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System.Diagnostics;
using System.Text.Json.Nodes;
using Newtonsoft.Json;
using Domain;
using Common.Cache;
using Utils;
using System.Data;
using DataAccess;

namespace Presentation.Controllers
{
    public class ArchiveController : Controller
    {
        private readonly ILogger<ArchiveController> _logger;

        public ArchiveController(ILogger<ArchiveController> logger)
        {
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View();
        }


    }
}

Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Controllers/HelpController.cs
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System.Diagnostics;
using System.Text.Json.Nodes;
using Newtonsoft.Json;
using Domain;
using Common.Cache;
using Utils;
using System.Data;
using DataAccess;

namespace Presentation.Controllers
{
    public class HelpController : Controller
    {
        private readonly ILogger<HelpController> _logger;

        public HelpController(ILogger<HelpController> logger)
        {
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AboutUs()
        {
            return View();
        }
        public ActionResult Help()
        {
            return View();
        }


    }
}

Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Controllers/ProccessController.cs
using Common.Cache;
using Domain;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Reflection;
using System.Text.Json.Nodes;

namespace Presentation.Controllers
{
    public class ProccessController : Controller
    {
        private readonly ILogger<ProccessController> _logger;

        public ProccessController(ILogger<ProccessController> logger)
        {
            _logger = logger;
        }

        public ActionResult Personal()
        {
            return View();
        }
        public ActionResult Finance()
        {
            return View();
        }
        public ActionResult Security()
        {
            return View();
        }
        public ActionResult Project()
        {
            return View();
        }
        public JsonResult GetUser()
        {
            var userData = new
            {
                UserLoginCache.Id,
                UserLoginCache.Rol,
                UserLoginCache.DescriptionRol,
                UserLoginCache.Email,
                UserLoginCache.Lastname,
                UserLoginCache.Name,
                UserLoginCache.Photo,
                UserLoginCache.Phone,
                UserLoginCache.IdentificationCard,
                UserLoginCache.Password,
                UserLoginCache.State

            };
            var jsonResult = new JsonResult(userData);
            return jsonResult;
        }
        public JsonResult GetRoles()
        {
            UserModel userModel = new UserModel();
            var jsonResult = new JsonResult(userModel.GetPerfilUser());
            return jsonResult;
        }
        public JsonResult GetUsers()
        {
            UserModel userModel = new UserModel();
            var jsonResult = new JsonResult(userModel.GetUsersWithRole());
            return jsonResult;
        }
        public JsonResult GetUsersWithoutRol()
        {
            UserModel userModel = new UserModel();
            var jsonResult = new JsonResult(userModel.GetUsersWithoutRole());
            return jsonResult;
        }
        public JsonResult GetEmployees()
        {
            UserModel userModel = new UserModel();
            var jsonResult = new JsonResult(userModel.GetEmployees());
            return jsonResult;
        }
       
        [HttpPost]
        public Boolean AssignRole([FromBody] JsonObject users)
        {
            UserModel userModel = new UserModel();
            return userModel.AssignRole(users);
        }
        [HttpPost]
        public Boolean ChangePassword([FromBody] JsonObject passwords)
        {
            UserModel userModel = new UserModel();
            return userModel.ChangePassword(passwords);
        }

    }
}

Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System.Diagnostics;
using System.Text.Json.Nodes;
using Newtonsoft.Json;
using Domain;
using Common.Cache;
using Utils;
using System.Data;
using DataAccess;

namespace Presentation.Controllers
{
    public class ReportsController : Controller
    {
        private readonly ILogger<ReportsController> _logger;

        public ReportsController(ILogger<ReportsController> logger)
        {
            _logger = logger;
        }
        public ActionResult Personal()
        {
            return View();
        }
        public ActionResult Finance()
        {
            return View();
        }
        public ActionResult Security()
        {
            return View();
        }
        public ActionResult Project()
        {
            return View();
        }
        public JsonResult GetUsers()
        {
            UserModel userModel = new UserModel();
            var jsonResult = new JsonResult(userModel.GetUsersWithRole());
            return jsonResult;
        }
        [HttpPost]
        public Boolean DownloadReports([FromBody] JsonObject users)
        {
            UserModel userModel = new UserModel();
            return userModel.DownloadReport(users);
        }


    }
}

Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Controllers/SharedController.cs
using Microsoft.AspNetCore.Mvc;
using Presentation.Models;
using System.Diagnostics;
using System.Text.Json.Nodes;
using Common.Cache;

namespace Presentation.Controllers
{
    public class SharedController : Controller
    {
        private readonly ILogger<SharedController> _logger;

        public SharedController(ILogger<SharedController> logger)
        {
            _logger = logger;
        }
        
        public string GetUser()
        {
            return UserLoginCache.Rol.ToString();
        }
    }
}

Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Views/Shared/Navbar.cshtml
@using Common.Cache;
<div class="container">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Application" asp-action="Index">Inicio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        @for (int i = 0; i < Common.Cache.Positions.Id.Count; i++)
                        {
                            if (Common.Cache.Positions.Id[i].ToString() == "A")
                            {
                                <a class="nav-link dropdown-toggle"
                                   id="navbarScrollingDropdown"
                                   role="button"
                                   data-bs-toggle="dropdown"
                                   aria-expanded="false">
                                    Archivo
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Archive" asp-action="Index">Conectar</a></li>
                                    <li><a class="dropdown-item">Desconectar</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item">Importar</a></li>
                                    <li><a class="dropdown-item">Exportar</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Salir</a></li>
                                </ul>
                            }
                        }
                    </li>
                    <li class="nav-item dropdown">
                        @for (int i = 0; i < Common.Cache.Positions.Id.Count; i++)
                        {
                            if (Common.Cache.Positions.Id[i].ToString() == "E")
                            {
                                <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Edición
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                    <li><a class="dropdown-item">Copiar</a></li>
                                    <li><a class="dropdown-item">Cortar</a></li>
                                    <li><a class="dropdown-item">Pegar</a></li>
                                    <li><a class="dropdown-item">Buscar</a></li>
                                    <li><a class="dropdown-item">Reemplazar</a></li>

                                </ul>
                            }
                        }
                    </li>
                    <li class="nav-item dropdown">
                        @for (int i = 0; i < Common.Cache.Positions.Id.Count; i++)
                        {
                            if (Common.Cache.Positions.Id[i].ToString() == "G")
                            {
                                <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Gestión
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                    <li><a class="dropdown-item" asp-controller="Management" asp-action="Personal">Personal</a></li>
                                    <li><a class="dropdown-item" asp-controller="Management" asp-action="Roles">Perfiles</a></li>
                                    <li><a class="dropdown-item" asp-controller="Management" asp-action="Finance">Finanzas</a></li>
                                    <li><a class="dropdown-item" asp-controller="Management" asp-action="Security">Seguridad</a></li>
                                    <li><a class="dropdown-item" asp-controller="Management" asp-action="Project">Proyectos</a></li>
                                </ul>
                            }
                        }
                    </li>
                    <li class="nav-item dropdown">
                        @for (int i = 0; i < Common.Cache.Positions.Id.Count; i++)
                        {
                            if (Common.Cache.Positions.Id[i].ToString() == "P")
                            {
                                <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Procesos
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                    <li><a class="dropdown-item" asp-controller="Proccess" asp-action="Personal">Personal</a></li>
                                    <li><a class="dropdown-item" asp-controller="Proccess" asp-action="Finance">Finanzas</a></li>
                                    <li><a class="dropdown-item" asp-controller="Proccess" asp-action="Security">Seguridad</a></li>
                                    <li><a class="dropdown-item" asp-controller="Proccess" asp-action="Project">Proyectos</a></li>
                                </ul>
                            }
                        }
                    </li>
                    <li class="nav-item dropdown">
                        @for (int i = 0; i < Common.Cache.Positions.Id.Count; i++)
                        {
                            if (Common.Cache.Positions.Id[i].ToString() == "R")
                            {
                                <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Reportes
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                    <li><a class="dropdown-item" asp-controller="Reports" asp-action="Personal">Personal</a></li>
                                    <li><a class="dropdown-item" asp-controller="Reports" asp-action="Finance">Finanzas</a></li>
                                    <li><a class="dropdown-item" asp-controller="Reports" asp-action="Security">Seguridad</a></li>
                                    <li><a class="dropdown-item" asp-controller="Reports" asp-action="Project">Proyectos</a></li>

                                </ul>
                            }
                        }
                    </li>
                    <li class="nav-item dropdown">
                        @for (int i = 0; i < Common.Cache.Positions.Id.Count; i++)
                        {
                            if (Common.Cache.Positions.Id[i].ToString() == "H")
                            {
                                <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Ayuda
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                    <li><a class="dropdown-item" asp-controller="Help" asp-action="AboutUs">Acerca De</a></li>
                                    <li><a class="dropdown-item" asp-controller="Help" asp-action="Index">Índice</a></li>
                                    <li><a class="dropdown-item" asp-controller="Help" asp-action="Help">Ayuda en línea</a></li>
                                </ul>
                            }
                        }
                    </li>
                </ul>

            </div>

        </div>
    </nav>
</div>

Aplicaciones Distribuidas/PARCIAL3/SISTEMA EN DOTNET/LoginLayeredCSharpD/Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>